name: Hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
   branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "HelloWorld"
        shell: bash


  goodbye:
    runs-on: ubntu-latest
    steps:
      - name: goodbyeWorld
        run: echo "GoodByeWorld"
        shell: bash
